version: '3'

services:

  nginx-php7:
      container_name: bloopy-api
      build:
        context: .
        dockerfile: docker/nginx-php7/Dockerfile
      ports:
        - 8088:80
      environment:
        SKIP_COMPOSER: 1
        WEBROOT: /var/www/public
      volumes:
        - ./:/var/www
        - ./docker/nginx-php7/sites:/etc/nginx/sites-enabled
#        - ./docker/nginx-php7/logs:/var/log/nginx/
      links:
        - redis:127.0.0.1
      networks:
        - slim-network
  redis:
    container_name: bloopy-api-redis
    build: docker/redis
    ports:
    - 6379:6379
    environment:
    - REDIS_PORT=6379
    - REDIS_PASSWORD=123456
    command: redis-server --appendonly yes
    volumes:
    - ./docker/redis/data:/data
    networks:
    - slim-network

networks:
  slim-network:
    driver: "bridge"