version: '3'

services:
  slim-swoole:
      container_name: slim-swoole
      build:
        context: .
        dockerfile: docker/np7/Dockerfile
      ports:
        - 8099:80
      volumes:
        - ./:/var/www/html
        - ./docker/np7/nginx-sites:/etc/nginx/sites-enabled
      links:
        - redis:127.0.0.1
      networks:
        - slim-network
  redis:
    container_name: bloopy-api-redis
    build: docker/redis
    ports:
    - 6379:6379
    environment:
    - REDIS_PORT=6379
    - REDIS_PASSWORD=123456
    command: redis-server --appendonly yes
    volumes:
    - ./docker/redis/data:/data
    networks:
    - slim-network

networks:
  slim-network:
    driver: "bridge"
