version: '3'

services:
  php:
      container_name: php
      build:
        context: .
        dockerfile: docker/php/Dockerfile
      volumes:
        - ./:/home
      ports:
        - "666:666"
      command: php /home/server/server.php
      #stdin_open: true
      #tty: true
      networks:
        - slim-network
networks:
  slim-network:
    driver: "bridge"
